<?xml version='1.0' encoding="UTF-8" ?>
<schema
   targetNamespace="http://mapserver.gis.umn.edu/mapserver" 
   xmlns:ms="http://mapserver.gis.umn.edu/mapserver" 
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns="http://www.w3.org/2001/XMLSchema"
   xmlns:gml="http://www.opengis.net/gml/3.2"
   elementFormDefault="qualified" version="0.1" >

  <import namespace="http://www.opengis.net/gml/3.2"
          schemaLocation="https://schemas.opengis.net/gml/3.2.1/gml.xsd" />

  <element name="fruchtfolgeflaeche" 
           type="ms:fruchtfolgeflaecheType" 
           substitutionGroup="gml:AbstractFeature" />

  <complexType name="fruchtfolgeflaecheType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="wkb_geometry" type="gml:GeometryPropertyType" minOccurs="0" maxOccurs="1"/>
          <element name="t_id" minOccurs="0" type="integer"/>
          <element name="anrechenbar" minOccurs="0" type="double"/>
          <element name="bemerkung" minOccurs="0" type="string"/>
          <element name="code_qualitaet_kantonal" minOccurs="0" type="string"/>
          <element name="bezeichnung_qualitaet_kantonal" minOccurs="0" type="string"/>
          <element name="bemerkung_qualitaet_kantonal" minOccurs="0" type="string"/>
          <element name="kanton" minOccurs="0" type="string"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

</schema>
