"""Base class shared by all dynamically-generated IlisMeta16 metamodel classes.

Generated by interlis.metamodel.registry.
"""

import itertools
from typing import Any

from pydantic import BaseModel, ConfigDict, PrivateAttr

_next_id = itertools.count(1)


class MetaInstance(BaseModel):
    """Common base class for all metamodel instances.

    `extra="allow"`: fields fed via an association (not declared in the
    class's own/inherited) are set dynamically by AttachmentResolver at
    build time, without needing to be pre-declared here (see
    interlis.metamodel.registry).
    """

    model_config = ConfigDict(extra="allow", arbitrary_types_allowed=True, validate_assignment=False)

    _qualified_class: str = PrivateAttr(default="")
    _source_ctx: Any | None = PrivateAttr(default=None)
    _id: int = PrivateAttr(default_factory=lambda: next(_next_id))
    # topicDef case only: the twin SubModel and DataUnit built for the same
    # TOPIC (not a formal IlisMeta16 association - see
    # interlis.builder.model_builder).
    _twin: "MetaInstance | None" = PrivateAttr(default=None)
    # classDef case only: True once its own `OID AS .../NO OID` clause has
    # been scanned (even if unresolved) - tells the enclosing topicDef's
    # class-default OID propagation not to override this class's own
    # decision (see InterlisModelBuilder._attach_class_oid).
    _own_oid_clause: bool = PrivateAttr(default=False)

    def __repr__(self) -> str:
        name = getattr(self, "Name", None)
        suffix = f" Name={name!r}" if name is not None else ""
        return f"<{self._qualified_class}{suffix} id={self._id}>"
